version: "3.8"
services:

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - redblue_net

  nginx-waf:
    image: theonemule/docker-waf:latest   
    container_name: nginx-waf
    restart: unless-stopped
    ports:
      - "8080:80"   
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./modsecurity:/etc/modsecurity:ro
    networks:
      - redblue_net
    depends_on:
      - juice-shop

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - observability

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - observability
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  redblue_net:
  observability:
